# local
mongo:
    host: 114.80.150.196
    port: 27777
    db_name : second_hand
    coll_comm : deal_price_test_test

# online
#mongo:
#    host: 192.168.0.43
#    port: 27017
#    db_name : fangjia
#    coll_comm : deal_price
